setup:
    python3 -m venv .venv && .venv/bin/pip install -e ".[dev]"

worker:
    .venv/bin/python -m src.worker

start *ARGS:
    .venv/bin/python -m src.starter {{ARGS}}

interactive *ARGS:
    .venv/bin/python -m src.interactive {{ARGS}}

test:
    .venv/bin/pytest tests/ -v
